name: strip
version: 0.0.0
license: MIT
copyright: (c) 2013 Simon Hengel
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

dependencies:
 - base == 4.*

library:
  source-dirs: src

tests:
  spec:
    defaults: sol/hpack-defaults@e2f7990163fdbcfa884a9e3202664122f9f6cd24
    dependencies:
      - strip
      - hspec == 2.*
